# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0002_auto_20171120_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='dataFim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='dataInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
