# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_auto_20171120_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatovaga',
            name='codigoVaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaga_candidato', to='eleicao.Vaga'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='codigoVaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaga_eleicao', to='eleicao.Vaga'),
        ),
    ]
