# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0004_auto_20171120_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urna',
            name='codigoCandidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_urna', to='eleicao.CandidatoVaga'),
        ),
        migrations.AlterField(
            model_name='urna',
            name='codigoEleicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urna_eleicao', to='eleicao.Eleicao'),
        ),
    ]
