# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0007_auto_20171120_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urna',
            name='codigoCandidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_urna', to='eleicao.Candidato'),
        ),
    ]
